### ISSUE TITLE
Maven repository jars compiled with Java 8

### ISSUE THREAD

**Issue by PurpleRus** [STIXProject/java-stix#1]
Our project's customer has specified Java 7 in their deployment enviroment, but when I run the STIX jar against a version 7 JRE I get a:

java.lang.UnsupportedClassVersionError: org/mitre/cybox/common_2/ObjectPropertiesType : Unsupported major.minor version 52.0

And wikipedia (http://en.wikipedia.org/wiki/Java_class_file) says than version 52.0 is for J2SE 8. This project's README says that the project builds under version 7, so would it be possible to provide the maven repository jars compiled under that version of the JDK?

**Comment by anlklsim** [comment]
We also needed this project compiled for Java7, for our production server.  I was successful in re-compiling the codebase with Java 7.   You are welcome to the jar file, but not sure how to get it to you.

**Comment by PurpleRus** [comment]
We should be able to build ourselves if it comes to that, but was hoping that the project owners might see it as a preferred option to provide that jars as fully Java 7 compatible 'out of the box'. Thanks.

**Comment by nemonik** [comment]
Yes, the libraries were built targeting Java 8 compatibility as Java 7 is at end of life as of April 2015 as per https://www.java.com/en/download/faq/java_7.xml.   I've since modified the Gradle build script for branches: master, v1.1.1.1, and v1.2.0.1 to build targeting Java 1.7 compatibility, and have verified.  Jars for the latter two branches won’t appear in the maven central repo until work on each is completed, and they are tagged as releases.  They have patches for their previous respective releases.  At that time, you will have Java 7 compatibility 'out of the box' across the schema versions supported by these.  Mind you, I’ve done all this in my clone of the repo…  although, travis ci and circleci  would appear to have passed my unit tests upon commit.

**Comment by martosoler** [comment]
Sorry for asking on a closed issue but what's the target date for having those releases with JDK 7 support? Thanks
